#!/usr/bin/env python

import sys
import os
from distutils.spawn import find_executable

try:
    cwd = os.getcwd()
    os.chdir(os.path.dirname(sys.argv[0]))
    sys.path.append("../../..")
    from hyperspeed import mistika
except ImportError:
    mistika = False

USAGE = """
manage detect
manage install
manage remove
"""

if len(sys.argv) < 2:
    print USAGE
    sys.exit(1)

action = sys.argv[1]
if action == "detect":
    pass
elif action == "install":
    activated = True
elif action == "remove":
    activated = False
else:
    print USAGE
    sys.exit(1)

new_config = ''
alias = "Hyperspeed"
file_path = os.path.abspath("../../../hyperspeed-dashboard.py")
stored = False
for line in open(mistika.tools_path):
    line_alias, line_path = line.strip().split()[:2]
    if file_path == line_path:
        if action == "detect":
            sys.exit(0)
        elif activated:
            new_config += '%s %s %%a\n' % (alias, file_path)
            stored = True
        else:
            continue
    else:
        line_path = find_executable(line_path)
        if line_path == None or not os.path.exists(line_path):
            continue
    new_config += line
if action == "detect":
    sys.exit(1)
if activated and not stored:
    new_config += '%s %s %%a\n' % (alias, file_path)
print '\nNew config:'
print new_config
open(mistika.tools_path, 'w').write(new_config)
